/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

import externalContracts from "./externalContracts";

const configExternalContracts = {
  ...externalContracts,
};

export default configExternalContracts;
